### PR TITLE
fix: reset action field after insert

### LINKED ISSUE #965: Réinitialiser le champs pour séléctionner une action lorsqu'on clique sur ajouter

### PR DESCRIPTION
**Pull request by lionelB**
close #965

### CODE REVIEW

File: src/lib/ui/base/Accordion.svelte [hunk 1]
```diff
@@ -1,14 +1,41 @@
...
 	const accordionId = `accordion-${$accordionCounter++}`;
 	const { registerAccordionItem, selectedItem } = getContext(ACCORDION);
 	registerAccordionItem(internalItemKey);
 	$: expanded = $selectedItem === internalItemKey;
+
+	let overflow = false;
+	let timeout;
+
+	function disclose() {
+		// this is a fix to allow component with floating part that not be cropped by accordeon parent
```
Comment (vjousse) [inline src/lib/ui/base/Accordion.svelte:17]:
```suggestion
		// this is a fix to allow a component with a floating part to not be cropped by the parent accordeon
```

**Review by vjousse — APPROVED** [review]
LGTM

File: src/lib/ui/base/Accordion.svelte (hunk 1 above)
Comment (lionelB) [reply src/lib/ui/base/Accordion.svelte:17]: merci vincent !
